name: gautambhamre
favicon: null
layout_spectrum: 0.08843899588100612
typography_spectrum: 0.3364456540439278
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.05627963109873235
  lightness: 0.720245482865721
  saturation: 0.039347140584141016
  rhythmicContrast: 0.4471179358661175
purpose: []
